# version: '3.8'

services:
    mariadb:
        container_name: mariadb
        networks:
            - inception
        build:
            context: requirements/mariadb
            dockerfile: Dockerfile
        volumes:
            - /home/edesaint/data/mariadb:/var/lib/mysql
        restart: always
        expose:
            - "3306"
    
    nginx:
        container_name: nginx
        volumes:
            - /home/edesaint/data/wordpress:/var/www/wordpress
        networks:
            - inception
        depends_on:
            - wordpress
        build: 
            context: requirements/nginx
            dockerfile: Dockerfile
        env_file: .env
        ports:
            - "443:443"
        restart: always
    
    wordpress:
        container_name: wordpress
        env_file: .env
        volumes:
            - /home/edesaint/data/wordpress:/var/www/wordpress/wp-content
        networks:
            - inception
        build: 
            context: requirements/wordpress
            dockerfile: Dockerfile
        depends_on:
            - mariadb
        restart: always
        expose: 
            - "9000"

volumes:
    wordpress:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/edesaint/data/wordpress'
    mariadb:
        driver: local
        driver_opts:
            type: 'none' 
            o: 'bind'
            device: '/home/edesaint/data/mariadb'

networks:
    inception:
        name: inception
        driver: bridge